/// Represents a canonical book of scripture, or a commonly
/// accepted deuterocanonical book.
pub const Book = enum(u16) {
    unknown = 0,
    genesis = 1,
    exodus = 2,
    leviticus = 3,
    numbers = 4,
    deuteronomy = 5,
    joshua = 6,
    judges = 7,
    ruth = 8,
    first_samuel = 9,
    second_samuel = 10,
    first_kings = 11,
    second_kings = 12,
    first_chronicles = 13,
    second_chronicles = 14,
    ezra = 15,
    nehemiah = 16,
    esther = 17,
    job = 18,
    psalms = 19,
    proverbs = 20,
    ecclesiastes = 21,
    song_of_solomon = 22,
    isaiah = 23,
    jeremiah = 24,
    lamentations = 25,
    ezekiel = 26,
    daniel = 27,
    hosea = 28,
    joel = 29,
    amos = 30,
    obadiah = 31,
    jonah = 32,
    micah = 33,
    nahum = 34,
    habakkuk = 35,
    zephaniah = 36,
    haggai = 37,
    zechariah = 38,
    malachi = 39,
    matthew = 40,
    mark = 41,
    luke = 42,
    john = 43,
    acts = 44,
    romans = 45,
    first_corinthians = 46,
    second_corinthians = 47,
    galatians = 48,
    ephesians = 49,
    philippians = 50,
    colossians = 51,
    first_thessalonians = 52,
    second_thessalonians = 53,
    first_timothy = 54,
    second_timothy = 55,
    titus = 56,
    philemon = 57,
    hebrews = 58,
    james = 59,
    first_peter = 60,
    second_peter = 61,
    first_john = 62,
    second_john = 63,
    third_john = 64,
    jude = 65,
    revelation = 66,
    first_samuel_k,
    second_samuel_k,
    tobit,
    tobit_s,
    tobit_ba,
    bel,
    bel_th,
    daniel_th,
    sirach,
    wisdom,
    psalms_of_solomon,
    odes,
    epistle_of_jeremiah,
    first_esdras,
    second_esdras,
    third_maccabees,
    fourth_maccabees,
    baruch,
    qohelet,
    joshua_a,
    joshua_b,
    judges_a,
    judges_b,
    third_kings,
    fourth_kings,
    judith,
    first_maccabees,
    second_maccabees,
    susannah,
    susannah_th,

    pub fn from_u16(value: u16) !Book {
        if (value > @intFromEnum(Book.susannah_th)) {
            return error.InvalidBook;
        }
        return @enumFromInt(value);
    }

    pub fn parse(value: []const u8) *const BookInfo {
        for (&NAMES) |*item| {
            for (item.*.names) |name| {
                if (std.ascii.eqlIgnoreCase(name, value)) {
                    return item;
                }
            }
        }
        return &NAMES[0];
    }

    pub fn info(self: Book) *const BookInfo {
        const index = @intFromEnum(self);
        if (index < NAMES.len) {
            return &NAMES[@intFromEnum(self)];
        }
        std.debug.print("Book.info({d}) is an invalid book number.\n", .{index});
        @panic("Book Enum contains invalid module id");
    }
};

const BookInfo = struct {
    names: []const []const u8,
    english: []const u8,
    english_short: []const u8,
    value: Book,
};

pub const NAMES = [_]BookInfo{
    .{
        .names = &.{ "unknown", "unk", "un" },
        .english = "Unknown",
        .english_short = "Unkn",
        .value = .unknown,
    },
    .{
        .names = &.{ "genesis", "gen", "gn" },
        .english = "Genesis",
        .english_short = "Gen",
        .value = .genesis,
    },
    .{
        .names = &.{ "exodus", "exo", "ex" },
        .english = "Exodus",
        .english_short = "Ex",
        .value = .exodus,
    },
    .{
        .names = &.{ "leviticus", "lev", "le", "lv" },
        .english = "Leviticus",
        .english_short = "Lev",
        .value = .leviticus,
    },
    .{
        .names = &.{ "numbers", "num", "nu", "nm", "nb" },
        .english = "Numbers",
        .english_short = "Num",
        .value = .numbers,
    },
    .{
        .names = &.{ "deuteronomy", "deut", "dt", "de" },
        .english = "Deuteronomy",
        .english_short = "Deut",
        .value = .deuteronomy,
    },
    .{
        .names = &.{ "joshua", "josh", "jos", "jsh", "jo" },
        .english = "Joshua",
        .english_short = "Josh",
        .value = .joshua,
    },
    .{
        .names = &.{ "judges", "judg", "jdg", "jg" },
        .english = "Judges",
        .english_short = "Judg",
        .value = .judges,
    },
    .{
        .names = &.{ "ruth", "rth", "ru" },
        .english = "Ruth",
        .english_short = "Ruth",
        .value = .ruth,
    },
    .{
        .names = &.{ "1 samuel", "1samuel", "1sam", "1sm", "1sa" },
        .english = "1 Samuel",
        .english_short = "1Sam",
        .value = .first_samuel,
    },
    .{
        .names = &.{ "2 samuel", "2samuel", "2sam", "2sm", "2sa" },
        .english = "2 Samuel",
        .english_short = "1Sam",
        .value = .second_samuel,
    },
    .{
        .names = &.{ "1 kings", "1kings", "1king", "1ki", "1kin", "1kgs" },
        .english = "1 Kings",
        .english_short = "1Ki",
        .value = .first_kings,
    },
    .{
        .names = &.{ "2 kings", "2kings", "2king", "2ki", "2kin", "2kgs" },
        .english = "2 Kings",
        .english_short = "2Ki",
        .value = .second_kings,
    },
    .{
        .names = &.{ "1 chronicles", "1chronicles", "1ch", "1chr", "1chron" },
        .english = "1 Chronicles",
        .english_short = "1Chr",
        .value = .first_chronicles,
    },
    .{
        .names = &.{ "2 chronicles", "2chronicles", "2ch", "2chr", "2chron" },
        .english = "2 Chronicles",
        .english_short = "2Chr",
        .value = .second_chronicles,
    },
    .{
        .names = &.{ "ezra", "ezr", "ez" },
        .english = "Ezra",
        .english_short = "Ezra",
        .value = .ezra,
    },
    .{
        .names = &.{ "nehemiah", "neh", "ne" },
        .english = "Nehemiah",
        .english_short = "Neh",
        .value = .nehemiah,
    },
    .{
        .names = &.{ "esther", "esth", "est", "es" },
        .english = "Esther",
        .english_short = "Est",
        .value = .esther,
    },
    .{
        .names = &.{ "job", "jb" },
        .english = "Job",
        .english_short = "Job",
        .value = .job,
    },
    .{
        .names = &.{ "psalms", "psalm", "ps", "pslm", "psm", "pss" },
        .english = "Psalms",
        .english_short = "Ps",
        .value = .psalms,
    },
    .{
        .names = &.{ "proverbs", "prov", "pv", "prv" },
        .english = "Proverbs",
        .english_short = "Prov",
        .value = .proverbs,
    },
    .{
        .names = &.{ "ecclesiastes", "eccl", "ecc", "eccle" },
        .english = "Ecclesiastes",
        .english_short = "Ecc",
        .value = .ecclesiastes,
    },
    .{
        .names = &.{ "song of solomon", "songofsolomon", "songs", "song", "sos", "cant" },
        .english = "SongOfSolomon", //TODO: post rust make english
        .english_short = "song",
        .value = .song_of_solomon,
    },
    .{
        .names = &.{ "isaiah", "isa", "is" },
        .english = "Isaiah",
        .english_short = "Isa",
        .value = .isaiah,
    },
    .{
        .names = &.{ "jeremiah", "jer", "je" },
        .english = "Jeremiah",
        .english_short = "Jer",
        .value = .jeremiah,
    },
    .{
        .names = &.{ "lamentations", "lam", "la" },
        .english = "Lamentations",
        .english_short = "Lam",
        .value = .lamentations,
    },
    .{
        .names = &.{ "ezekiel", "ezek", "eze", "ezk" },
        .english = "Ezekiel",
        .english_short = "Ezek",
        .value = .ezekiel,
    },
    .{
        .names = &.{ "daniel", "dan", "dn" },
        .english = "Daniel",
        .english_short = "Dan",
        .value = .daniel,
    },
    .{
        .names = &.{ "hosea", "hos", "ho" },
        .english = "Hosea",
        .english_short = "Hos",
        .value = .hosea,
    },
    .{
        .names = &.{ "joel", "jl" },
        .english = "Joel",
        .english_short = "Joel",
        .value = .joel,
    },
    .{
        .names = &.{ "amos", "am" },
        .english = "Amos",
        .english_short = "Amos",
        .value = .amos,
    },
    .{
        .names = &.{ "obadiah", "obad", "ob" },
        .english = "Obadiah",
        .english_short = "Obad",
        .value = .obadiah,
    },
    .{
        .names = &.{ "jonah", "jon", "jnh" },
        .english = "Jonah",
        .english_short = "Jonah",
        .value = .jonah,
    },
    .{
        .names = &.{ "micah", "mic", "mi" },
        .english = "Micah",
        .english_short = "Mic",
        .value = .micah,
    },
    .{
        .names = &.{ "nahum", "nah", "na" },
        .english = "Nahum",
        .english_short = "Nah",
        .value = .nahum,
    },
    .{
        .names = &.{ "habakkuk", "hab", "ha" },
        .english = "Habakkuk",
        .english_short = "Hab",
        .value = .habakkuk,
    },
    .{
        .names = &.{ "zephaniah", "zeph", "ze", "zp" },
        .english = "Zephaniah",
        .english_short = "Zeph",
        .value = .zephaniah,
    },
    .{
        .names = &.{ "haggai", "hag", "hg" },
        .english = "Haggai",
        .english_short = "Hag",
        .value = .haggai,
    },
    .{
        .names = &.{ "zechariah", "zech", "zec", "zc" },
        .english = "Zechariah",
        .english_short = "Zech",
        .value = .zechariah,
    },
    .{
        .names = &.{ "malachi", "mal", "ml" },
        .english = "Malachi",
        .english_short = "Mal",
        .value = .malachi,
    },
    .{
        .names = &.{ "matthew", "matt", "mt", "mat" },
        .english = "Matthew",
        .english_short = "Matt",
        .value = .matthew,
    },
    .{
        .names = &.{ "mark", "mrk", "mk", "mr", "mar" },
        .english = "Mark",
        .english_short = "Mark",
        .value = .mark,
    },
    .{
        .names = &.{ "luke", "luk", "lk" },
        .english = "Luke",
        .english_short = "Luke",
        .value = .luke,
    },
    .{
        .names = &.{ "john", "jhn", "joh", "jh" },
        .english = "John",
        .english_short = "John",
        .value = .john,
    },
    .{
        .names = &.{ "acts", "act", "ac" },
        .english = "Acts",
        .english_short = "Acts",
        .value = .acts,
    },
    .{
        .names = &.{ "romans", "rom", "ro", "rm" },
        .english = "Romans",
        .english_short = "Rom",
        .value = .romans,
    },
    .{
        .names = &.{
            "1 corinthians",
            "1corinthians",
            "firstcorinthians",
            "1cor",
            "1co",
            "first corinthians",
            "first_corinthians",
        },
        .english = "1 Corinthians",
        .english_short = "1Cor",
        .value = .first_corinthians,
    },
    .{
        .names = &.{
            "2 corinthians",
            "2corinthians",
            "secondcorinthians",
            "2cor",
            "2co",
            "second corinthians",
            "second_corinthians",
        },
        .english = "2 Corinthians",
        .english_short = "2Cor",
        .value = .second_corinthians,
    },
    .{
        .names = &.{ "galatians", "gal", "ga" },
        .english = "Galatians",
        .english_short = "Gal",
        .value = .galatians,
    },
    .{
        .names = &.{ "ephesians", "eph", "ep" },
        .english = "Ephesians",
        .english_short = "Eph",
        .value = .ephesians,
    },
    .{
        .names = &.{ "philippians", "phil", "php", "pp" },
        .english = "Philippians",
        .english_short = "Phil",
        .value = .philippians,
    },
    .{
        .names = &.{ "colossians", "col", "cl" },
        .english = "Colossians",
        .english_short = "Col",
        .value = .colossians,
    },
    .{
        .names = &.{
            "1 thessalonians",
            "1thessalonians",
            "firstthessalonians",
            "1thess",
            "1th",
            "first thessalonians",
            "first_thessalonians",
        },
        .english = "1 Thessalonians",
        .english_short = "1Th",
        .value = .first_thessalonians,
    },
    .{
        .names = &.{
            "2 thessalonians",
            "2thessalonians",
            "secondthessalonians",
            "2thess",
            "2th",
            "second thessalonians",
            "second_thessalonians",
        },
        .english = "2 Thessalonians",
        .english_short = "2Th",
        .value = .second_thessalonians,
    },
    .{
        .names = &.{
            "1 timothy",
            "1timothy",
            "firsttimothy",
            "1tim",
            "1ti",
            "first timothy",
            "first_timothy",
        },
        .english = "1 Timothy",
        .english_short = "1Tim",
        .value = .first_timothy,
    },
    .{
        .names = &.{
            "2 timothy",
            "2timothy",
            "secondtimothy",
            "2tim",
            "2ti",
            "second timothy",
            "second_timothy",
        },
        .english = "2 Timothy",
        .english_short = "2Tim",
        .value = .second_timothy,
    },
    .{
        .names = &.{ "titus", "tit", "ti" },
        .english = "Titus",
        .english_short = "Tit",
        .value = .titus,
    },
    .{
        .names = &.{ "philemon", "phm", "philem", "phlm" },
        .english = "Philemon",
        .english_short = "Phm",
        .value = .philemon,
    },
    .{
        .names = &.{ "hebrews", "heb", "he" },
        .english = "Hebrews",
        .english_short = "Heb",
        .value = .hebrews,
    },
    .{
        .names = &.{ "james", "jam", "jas", "jm" },
        .english = "James",
        .english_short = "Jas",
        .value = .james,
    },
    .{
        .names = &.{
            "1 peter",
            "1peter",
            "firstpeter",
            "1pet",
            "1pe",
            "1pt",
            "first peter",
            "first_peter",
        },
        .english = "1 Peter",
        .english_short = "1Pet",
        .value = .first_peter,
    },
    .{
        .names = &.{
            "2 peter",
            "2peter",
            "secondpeter",
            "2pet",
            "2pe",
            "second peter",
            "second_peter",
        },
        .english = "2 Peter",
        .english_short = "2Pet",
        .value = .second_peter,
    },
    .{
        .names = &.{
            "1 john",
            "1john",
            "firstjohn",
            "1jn",
            "1 jn",
            "1jh",
            "1 jh",
            "1jo",
            "1jhn",
            "1joh",
            "first_john",
        },
        .english = "1 John",
        .english_short = "1Jn",
        .value = .first_john,
    },
    .{
        .names = &.{
            "2 john",
            "2john",
            "secondjohn",
            "2jn",
            "2 jn",
            "2jh",
            "2 jh",
            "2jo",
            "2jhn",
            "2joh",
            "second_john",
        },
        .english = "2 John",
        .english_short = "2Jn",
        .value = .second_john,
    },
    .{
        .names = &.{
            "3 john",
            "3john",
            "thirdjohn",
            "3jn",
            "3 jn",
            "3jh",
            "3 jh",
            "3jo",
            "3joh",
            "3jhn",
            "third_john",
        },
        .english = "3 John",
        .english_short = "3Jn",
        .value = .third_john,
    },
    .{
        .names = &.{ "jude", "jud", "ju", "jde" },
        .english = "Jude",
        .english_short = "Jude",
        .value = .jude,
    },
    .{
        .names = &.{ "revelation", "rev", "re", "rv" },
        .english = "Revelation",
        .english_short = "Rev",
        .value = .revelation,
    },
    .{
        .names = &.{
            "1 samuel-k",
            "1samuel-k",
            "firstsamuel-k",
            "1 sam-k",
            "1sam-k",
            "1sa-k",
            "1samk",
        },
        .english = "1Sam-K", //TODO make english post rust
        .english_short = "1SamK",
        .value = .first_samuel_k,
    },
    .{
        .names = &.{
            "2 samuel-k",
            "2samuel-k",
            "secondsamuel-k",
            "2 sam-k",
            "2sam-k",
            "2sa-k",
            "2samk",
        },
        .english = "2Sam-K", //TODO make english post rust
        .english_short = "2SamK",
        .value = .second_samuel_k,
    },
    .{
        .names = &.{ "tobit", "tobbit", "tob" },
        .english = "Tobit",
        .english_short = "Tob",
        .value = .tobit,
    },
    .{
        .names = &.{ "tobits", "tobs", "tobit s", "tobit_s" },
        .english = "TobitS",
        .english_short = "TobS",
        .value = .tobit_s,
    },
    .{
        .names = &.{ "tobitba", "tobba", "tobit ba", "tobit_ba" },
        .english = "TobitBA",
        .english_short = "TobBA",
        .value = .tobit_ba,
    },
    .{
        .names = &.{ "bel", "bell" },
        .english = "Bel",
        .english_short = "Bel",
        .value = .bel,
    },
    .{
        .names = &.{ "belth", "bellth", "bel th", "bel_th" },
        .english = "BelTh",
        .english_short = "BelTh",
        .value = .bel_th,
    },
    .{
        .names = &.{ "daniel th", "danielth", "daniel_th" },
        .english = "DanielTh",
        .english_short = "DanTh",
        .value = .daniel_th,
    },
    .{
        .names = &.{ "sirach", "sir" },
        .english = "Sirach",
        .english_short = "Sira",
        .value = .sirach,
    },
    .{
        .names = &.{ "wisdom", "wis" },
        .english = "Wisdom",
        .english_short = "Wis",
        .value = .wisdom,
    },
    .{
        .names = &.{ "psalmsofsolomon", "psalms of solomon", "pos", "pss", "psalms_of_solomon" },
        .english = "PsalmsOfSolomon", //TODO post rust add spaces
        .english_short = "Pos",
        .value = .psalms_of_solomon,
    },
    .{
        .names = &.{ "odes", "ode", "od" },
        .english = "Odes",
        .english_short = "Odes",
        .value = .odes,
    },
    .{
        .names = &.{ "epistleofjeremiah", "eoj", "epistle of jeremiah", "epistle_of_jeremiah" },
        .english = "EpistleOfJeremiah", //TODO: post rust make english
        .english_short = "Eoj",
        .value = .epistle_of_jeremiah,
    },
    .{
        .names = &.{ "firstesdras", "1 esdras", "1esdras", "1es", "first esdras", "first_esdras" },
        .english = "1 Esdras",
        .english_short = "1Es",
        .value = .first_esdras,
    },
    .{
        .names = &.{ "secondesdras", "2 esdras", "2esdras", "2es", "second esdras", "second_esdras" },
        .english = "2 Esdras",
        .english_short = "2Es",
        .value = .second_esdras,
    },
    .{
        .names = &.{ "thirdmaccabees", "3 maccabees", "3maccabees", "third maccabees", "third_maccabees" },
        .english = "3 Maccabees",
        .english_short = "3Mac",
        .value = .third_maccabees,
    },
    .{
        .names = &.{ "fourthmaccabees", "4 maccabees", "4maccabees", "fourth maccabees", "fourth_maccabees" },
        .english = "4 Maccabees",
        .english_short = "4Mac",
        .value = .fourth_maccabees,
    },
    .{
        .names = &.{ "baruch", "bar" },
        .english = "Baruch",
        .english_short = "Bar",
        .value = .baruch,
    },
    .{
        .names = &.{ "qohelet", "qoh", "kohelet" },
        .english = "Qohelet",
        .english_short = "Qoh",
        .value = .qohelet,
    },
    .{
        .names = &.{ "joshuaa", "josha", "joshua a", "joshua_a" },
        .english = "JoshuaA",
        .english_short = "JoshA",
        .value = .joshua_a,
    },
    .{
        .names = &.{ "joshuab", "joshb", "joshua_b", "joshua b" },
        .english = "JoshuaB",
        .english_short = "JoshB",
        .value = .joshua_b,
    },
    .{
        .names = &.{ "judgesa", "judga", "judges a", "judges_a" },
        .english = "JudgesA",
        .english_short = "JudgA",
        .value = .judges_a,
    },
    .{
        .names = &.{ "judgesb", "judgb", "judges b", "judges_b" },
        .english = "JudgesB",
        .english_short = "JudgB",
        .value = .judges_b,
    },
    .{
        .names = &.{ "3 kings", "3kings", "3king", "three kings", "three_kings" },
        .english = "3 Kings",
        .english_short = "3King",
        .value = .third_kings,
    },
    .{
        .names = &.{ "4 kings", "4kings", "4king", "four kings", "four_kings" },
        .english = "4 Kings",
        .english_short = "4King",
        .value = .fourth_kings,
    },
    .{
        .names = &.{"judith"},
        .english = "Judith",
        .english_short = "Jdth",
        .value = .judith,
    },
    .{
        .names = &.{ "firstmaccabees", "1 maccabees", "1maccabees", "first macabees", "first_maccabees" },
        .english = "1 Maccabees",
        .english_short = "1Mac",
        .value = .first_maccabees,
    },
    .{
        .names = &.{ "secondmaccabees", "2 maccabees", "2maccabees", "second maccabees", "second_maccabees" },
        .english = "2 Maccabees",
        .english_short = "2Mac",
        .value = .second_maccabees,
    },
    .{
        .names = &.{ "susannah", "sus" },
        .english = "Susannah",
        .english_short = "Sus",
        .value = .susannah,
    },
    .{
        .names = &.{ "susannahth", "susannah th", "susth", "sus th", "susannah_th", "sus_th" },
        .english = "SusannahTh",
        .english_short = "SusTh",
        .value = .susannah_th,
    },
};

const std = @import("std");

test "book_parse" {
    try std.testing.expectEqual(Book.mark, Book.parse("Mark").value);
    try std.testing.expectEqual(Book.first_john, Book.parse("1jh").value);
}
