name: Praxis Tests

on:
  push: 
    branches: [master, experimental]

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    name: Build and Test Praxis on Ubuntu (zig master)
    steps:
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v2
        with:
          version: master
      - run: zig build test
  test-mac-master:
    runs-on: macos-latest
    name: Build and Test Praxis on MacOS (zig master)
    steps:
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v2
        with:
          version: master
      - run: zig build test
  test-mac-16:
    runs-on: macos-latest
    name: Build and Test Praxis on MacOS (zig 0.16.0)
    steps:
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v2
        with:
          version: 0.16.0
      - run: zig build test

